export default {
  extends: ['@commitlint/config-conventional', '@commitlint/parse'],
  rules: {
    'header-max-length': [2, 'always', 50],
    'subject-case': [2, 'always', 'sentence-case'],
    'type-enum': [
      2,
      'always',
      [
        'style',
        'perf',
        'prune',
        'fix',
        'hotfix',
        'feature',
        'docs',
        'deploy',
        'ui',
        'init',
        'test',
        'security',
        'osx',
        'linux',
        'windows',
        'android',
        'ios',
        'release',
        'lint',
        'wip',
        'fix-ci',
        'downgrade',
        'upgrade',
        'pushpin',
        'ci',
        'analytics',
        'refactoring',
        'docker',
        'dep-add',
        'dep-rm',
        'config',
        'i18n',
        'typo',
        'poo',
        'revert',
        'merge',
        'dep-up',
        'compat',
        'mv',
        'license',
        'breaking',
        'assets',
        'review',
        'access',
        'docs-code',
        'beer',
        'texts',
        'db',
        'log-add',
        'log-rm',
        'contrib-add',
        'ux',
        'arch',
        'responsive',
        'mock',
        'egg',
        'gitignore',
        'snapshot',
        'experiment',
        'seo',
        'k8s',
        'types',
        'seed',
        'flags',
        'animation',
        'todo',
      ],
    ],
  },
  parserPreset: './index.js',
  parserOpts: {
    // eslint-disable-next-line prefer-named-capture-group
    headerPattern: /^(.*?)(?:\((.*?)\))?!?:\s(?:(.)\s)?(.*)$/u,
    headerCorrespondence: ['type', 'scope', 'emoji', 'subject'],
    // eslint-disable-next-line prefer-named-capture-group
    revertPattern: /^(revert):\s(?:(.)\s)?(\w{7})\s-\s(.*?)$/u,
    revertCorrespondence: ['type', 'emoji', 'hash', 'subject'],
  },
};
